//HintName: SubcommandsTest_A.g.cs
// <auto-generated/>
using global::System.CommandLine.SourceGenerator.Common;

namespace System.CommandLine.SourceGenerator.Tests
{
    public static class SubcommandsTest_AFactory
    {
        public static global::System.CommandLine.Command Create()
        {
            var symbol = new global::System.CommandLine.Option<global::System.Int32>("--option2", null);
            var cmd = new global::System.CommandLine.Command("A", null);
            cmd.AddOption(symbol);
            cmd.AddCommand(global::System.CommandLine.SourceGenerator.Tests.SubcommandsTest_BFactory.Create());
            return cmd;
        }
    }
}
