//HintName: StructTest.g.cs
// <auto-generated/>
using global::System.CommandLine.SourceGenerator.Common;

namespace System.CommandLine.SourceGenerator.Tests
{
    public static class StructTestFactory
    {
        public static global::System.CommandLine.RootCommand Create()
        {
            var symbol = new global::System.CommandLine.Option<global::System.String>("--hello", null);
            var cmd = new global::System.CommandLine.RootCommand("")
            {
                Handler = new StructTestCommandHandler(symbol)
            };
            cmd.AddOption(symbol);
            return cmd;
        }

        private sealed class StructTestCommandHandler : global::System.CommandLine.Invocation.ICommandHandler
        {
            private readonly global::System.CommandLine.Binding.IValueDescriptor<global::System.String> _symbolHello;

            public StructTestCommandHandler(
                global::System.CommandLine.Binding.IValueDescriptor<global::System.String> symbolHello)
            {
                _symbolHello = symbolHello;
            }

            public int Invoke(global::System.CommandLine.Invocation.InvocationContext context)
            {
                return InvokeAsync(context).Result;
            }

            public global::System.Threading.Tasks.Task<int> InvokeAsync(global::System.CommandLine.Invocation.InvocationContext context)
            {
                var command = new global::System.CommandLine.SourceGenerator.Tests.StructTest()
                {
                    Hello = ValueDesriptorHelper.GetValueForHandlerParameter<global::System.String>(_symbolHello, context)
                };
                var handler = new global::System.CommandLine.SourceGenerator.Tests.StructTestHandler();
                return handler.InvokeAsync(command);
            }
        }
    }
}
