//HintName: SubcommandsTest.g.cs
// <auto-generated/>
using global::System.CommandLine.SourceGenerator.Common;

namespace System.CommandLine.SourceGenerator.Tests
{
    public static class SubcommandsTestFactory
    {
        public static global::System.CommandLine.RootCommand Create()
        {
            var symbol = new global::System.CommandLine.Option<global::System.Int32>("--option1", null);
            var cmd = new global::System.CommandLine.RootCommand("");
            cmd.AddOption(symbol);
            cmd.AddCommand(global::System.CommandLine.SourceGenerator.Tests.SubcommandsTest_AFactory.Create());
            return cmd;
        }
    }
}
