//HintName: DerviedTest.g.cs
// <auto-generated/>
using global::System.CommandLine.SourceGenerator.Common;

namespace System.CommandLine.SourceGenerator.Tests
{
    public static class DerviedTestFactory
    {
        public static global::System.CommandLine.RootCommand Create()
        {
            var symbol = new global::System.CommandLine.Option<global::System.Int32>("--virtual-has-option-override", null);
            var symbol1 = new global::System.CommandLine.Option<global::System.Int32>("--virtual-no-option", null);
            var symbol2 = new global::System.CommandLine.Option<global::System.Int32>("--option", null);
            var cmd = new global::System.CommandLine.RootCommand("");
            cmd.AddOption(symbol);
            cmd.AddOption(symbol1);
            cmd.AddOption(symbol2);
            return cmd;
        }
    }
}
