//HintName: SubCommandTest_B.g.cs
// <auto-generated/>
using global::System.CommandLine.SourceGenerator.Common;

namespace System.CommandLine.SourceGenerator.Tests
{
    public class SubCommandTest_BOptions
    {
        public ICommandHandler<global::System.CommandLine.SourceGenerator.Tests.SubCommandTest_B> Handler { get; set; }

        public SubCommandTest_SubOptions SubCommandTest_SubOptions { get; set; }
    }

    public static class SubCommandTest_BFactory
    {
        public static global::System.CommandLine.Command Create()
        {
            return Create(null);
        }

        public static global::System.CommandLine.Command Create(SubCommandTest_BOptions options)
        {
            ICommandHandler<global::System.CommandLine.SourceGenerator.Tests.SubCommandTest_B> handler = null;
            if (options != null)
                handler = options.Handler;
            global::System.CommandLine.Invocation.ICommandHandler handlerAdapter = null;
            if (handler != null)
                handlerAdapter = new SubCommandTest_BCommandHandlerAdapter(handler);
            var cmd = new global::System.CommandLine.Command("B", null)
            {
                Handler = handlerAdapter
            };
            if (options != null && options.SubCommandTest_SubOptions != null)
            {
                cmd.AddCommand(SubCommandTest_SubFactory.Create(options.SubCommandTest_SubOptions));
            }
            else
            {
                cmd.AddCommand(SubCommandTest_SubFactory.Create());
            }
            return cmd;
        }

        private sealed class SubCommandTest_BCommandHandlerAdapter : global::System.CommandLine.Invocation.ICommandHandler
        {
            private readonly ICommandHandler<global::System.CommandLine.SourceGenerator.Tests.SubCommandTest_B> _commandHandler;

            public SubCommandTest_BCommandHandlerAdapter(ICommandHandler<global::System.CommandLine.SourceGenerator.Tests.SubCommandTest_B> commandHandler)
            {
                _commandHandler = commandHandler;
            }

            public int Invoke(global::System.CommandLine.Invocation.InvocationContext context)
            {
                return InvokeAsync(context).Result;
            }

            public global::System.Threading.Tasks.Task<int> InvokeAsync(global::System.CommandLine.Invocation.InvocationContext context)
            {
                var command = new global::System.CommandLine.SourceGenerator.Tests.SubCommandTest_B();
                return _commandHandler.InvokeAsync(command);
            }
        }
    }
}
