//HintName: SubCommandTest_Sub.g.cs
// <auto-generated/>
using global::System.CommandLine.SourceGenerator.Common;

namespace System.CommandLine.SourceGenerator.Tests
{
    public class SubCommandTest_SubOptions
    {
        public ICommandHandler<global::System.CommandLine.SourceGenerator.Tests.SubCommandTest_Sub> Handler { get; set; }
    }

    public static class SubCommandTest_SubFactory
    {
        public static global::System.CommandLine.Command Create()
        {
            return Create(null);
        }

        public static global::System.CommandLine.Command Create(SubCommandTest_SubOptions options)
        {
            ICommandHandler<global::System.CommandLine.SourceGenerator.Tests.SubCommandTest_Sub> handler = null;
            if (options != null)
                handler = options.Handler;
            global::System.CommandLine.Invocation.ICommandHandler handlerAdapter = null;
            if (handler != null)
                handlerAdapter = new SubCommandTest_SubCommandHandlerAdapter(handler);
            var cmd = new global::System.CommandLine.Command("Sub", null)
            {
                Handler = handlerAdapter
            };
            return cmd;
        }

        private sealed class SubCommandTest_SubCommandHandlerAdapter : global::System.CommandLine.Invocation.ICommandHandler
        {
            private readonly ICommandHandler<global::System.CommandLine.SourceGenerator.Tests.SubCommandTest_Sub> _commandHandler;

            public SubCommandTest_SubCommandHandlerAdapter(ICommandHandler<global::System.CommandLine.SourceGenerator.Tests.SubCommandTest_Sub> commandHandler)
            {
                _commandHandler = commandHandler;
            }

            public int Invoke(global::System.CommandLine.Invocation.InvocationContext context)
            {
                return InvokeAsync(context).Result;
            }

            public global::System.Threading.Tasks.Task<int> InvokeAsync(global::System.CommandLine.Invocation.InvocationContext context)
            {
                var command = new global::System.CommandLine.SourceGenerator.Tests.SubCommandTest_Sub();
                return _commandHandler.InvokeAsync(command);
            }
        }
    }
}
