//HintName: CommandTest_Full.g.cs
// <auto-generated/>
using global::System.CommandLine.SourceGenerator.Common;

namespace System.CommandLine.SourceGenerator.Tests
{
    public class CommandTest_FullOptions
    {
        public ICommandHandler<global::System.CommandLine.SourceGenerator.Tests.CommandTest_Full> Handler { get; set; }

        public CommandTest_SimpleOptions CommandTest_SimpleOptions { get; set; }
    }

    public static class CommandTest_FullFactory
    {
        public static global::System.CommandLine.Command Create()
        {
            return Create(null);
        }

        public static global::System.CommandLine.Command Create(CommandTest_FullOptions options)
        {
            ICommandHandler<global::System.CommandLine.SourceGenerator.Tests.CommandTest_Full> handler = null;
            if (options != null)
                handler = options.Handler;
            if (handler == null)
                handler = new global::System.CommandLine.SourceGenerator.Tests.CommandTest_Full_Handler();
            global::System.CommandLine.Invocation.ICommandHandler handlerAdapter = null;
            if (handler != null)
                handlerAdapter = new CommandTest_FullCommandHandlerAdapter(handler);
            var cmd = new global::System.CommandLine.Command("Name", "Description")
            {
                TreatUnmatchedTokensAsErrors = true,
                Handler = handlerAdapter,
                IsHidden = true
            };
            cmd.AddAlias("Aliases");
            if (options != null && options.CommandTest_SimpleOptions != null)
            {
                cmd.AddCommand(CommandTest_SimpleFactory.Create(options.CommandTest_SimpleOptions));
            }
            else
            {
                cmd.AddCommand(CommandTest_SimpleFactory.Create());
            }
            return cmd;
        }

        private sealed class CommandTest_FullCommandHandlerAdapter : global::System.CommandLine.Invocation.ICommandHandler
        {
            private readonly ICommandHandler<global::System.CommandLine.SourceGenerator.Tests.CommandTest_Full> _commandHandler;

            public CommandTest_FullCommandHandlerAdapter(ICommandHandler<global::System.CommandLine.SourceGenerator.Tests.CommandTest_Full> commandHandler)
            {
                _commandHandler = commandHandler;
            }

            public int Invoke(global::System.CommandLine.Invocation.InvocationContext context)
            {
                return InvokeAsync(context).Result;
            }

            public global::System.Threading.Tasks.Task<int> InvokeAsync(global::System.CommandLine.Invocation.InvocationContext context)
            {
                var command = new global::System.CommandLine.SourceGenerator.Tests.CommandTest_Full();
                return _commandHandler.InvokeAsync(command);
            }
        }
    }
}
